// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTjlYV4jOJ215CC0bW5eLL-UlLqRwKkPI',
    appId: '1:254814480166:web:4f7bd30ad98ec1aa0003e7',
    messagingSenderId: '254814480166',
    projectId: 'medic-b0f48',
    authDomain: 'medic-b0f48.firebaseapp.com',
    storageBucket: 'medic-b0f48.appspot.com',
    measurementId: 'G-W61125JW7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9DKIKkxjS05iVyr4PKRV5jtS2tGDIX_s',
    appId: '1:254814480166:android:ada5c0fb4c4804db0003e7',
    messagingSenderId: '254814480166',
    projectId: 'medic-b0f48',
    storageBucket: 'medic-b0f48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4EYfo8EumVMpEqkV5gIi_JyfDGiDSBuY',
    appId: '1:254814480166:ios:5ee170004db0a6900003e7',
    messagingSenderId: '254814480166',
    projectId: 'medic-b0f48',
    storageBucket: 'medic-b0f48.appspot.com',
    iosBundleId: 'com.example.medics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4EYfo8EumVMpEqkV5gIi_JyfDGiDSBuY',
    appId: '1:254814480166:ios:5ee170004db0a6900003e7',
    messagingSenderId: '254814480166',
    projectId: 'medic-b0f48',
    storageBucket: 'medic-b0f48.appspot.com',
    iosBundleId: 'com.example.medics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTjlYV4jOJ215CC0bW5eLL-UlLqRwKkPI',
    appId: '1:254814480166:web:4d467b9de643412e0003e7',
    messagingSenderId: '254814480166',
    projectId: 'medic-b0f48',
    authDomain: 'medic-b0f48.firebaseapp.com',
    storageBucket: 'medic-b0f48.appspot.com',
    measurementId: 'G-2YFWW4B94W',
  );
}
